/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    services: Service;
    'public-media': PublicMedia;
    staff: Staff;
    clients: Client;
    'portal-identities': PortalIdentity;
    'security-events': SecurityEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'public-media': PublicMediaSelect<false> | PublicMediaSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'portal-identities':
      PortalIdentitiesSelect<false> | PortalIdentitiesSelect<true>;
    'security-events': SecurityEventsSelect<false> | SecurityEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences':
      PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations':
      PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'es')
    | ('en' | 'es')[];
  globals: {
    'business-identity': BusinessIdentity;
    'contact-settings': ContactSetting;
    'portal-settings': PortalSetting;
    'homepage-content': HomepageContent;
  };
  globalsSelect: {
    'business-identity':
      BusinessIdentitySelect<false> | BusinessIdentitySelect<true>;
    'contact-settings':
      ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'portal-settings': PortalSettingsSelect<false> | PortalSettingsSelect<true>;
    'homepage-content':
      HomepageContentSelect<false> | HomepageContentSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: number;
  role: 'editor' | 'bilingual-reviewer' | 'publisher' | 'cms-admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Stable internal key. Lowercase letters, numbers, and hyphens only; cannot be changed after creation.
   */
  stableIdentifier: string;
  title: string;
  summary: string;
  detailedDescription?: string | null;
  displayOrder: number;
  /**
   * Inactive services remain in CMS history but are not eligible for future public projection.
   */
  isActive: boolean;
  /**
   * Controls the server-side bilingual review and publication policy.
   */
  contentPolicy: 'evergreen' | 'legal' | 'urgent-announcement';
  workingRevision: number;
  /**
   * Workflow metadata is editorial-only and must never include client-sensitive information.
   */
  translationWorkflow: {
    en: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
    es: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
  };
  /**
   * Required when an urgent announcement is published in one locale before the other.
   */
  urgentPublicationControls?: {
    expiresAt?: string | null;
    translationOwner?: (number | null) | CmsUser;
    translationFollowUpDeadline?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Public brand and marketing images only. Never upload tax records, identity or immigration documents, client photographs, private uploads, or case evidence.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-media".
 */
export interface PublicMedia {
  id: number;
  assetType: 'brand-logo' | 'brand-icon' | 'marketing-image';
  altText: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  firstName: string;
  lastName: string;
  workEmail: string;
  role: 'owner' | 'administrator' | 'case-worker' | 'intake';
  status: 'active' | 'disabled';
  /**
   * Server-owned primary-owner marker. Owner transfer is not supported.
   */
  isPrimaryOwner: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Server-generated business reference. It is not a database ID or credential and cannot be changed.
   */
  clientNumber: string;
  firstName: string;
  lastName: string;
  /**
   * Contact data only. Editing this value never changes login credentials or creates a portal identity.
   */
  contactEmail: string;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-identities".
 */
export interface PortalIdentity {
  id: number;
  authUserId: string;
  subjectType: 'staff' | 'client';
  staff?: (number | null) | Staff;
  client?: (number | null) | Client;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-events".
 */
export interface SecurityEvent {
  id: number;
  occurredAt: string;
  action:
    | 'primary-owner.bootstrap.succeeded'
    | 'primary-owner.bootstrap.failed'
    | 'authentication.succeeded'
    | 'authentication.failed'
    | 'session.ended'
    | 'mfa.enrollment.succeeded'
    | 'mfa.verification.succeeded'
    | 'mfa.verification.failed'
    | 'domain-subject.disabled'
    | 'authorization.denied';
  actorKind:
    | 'anonymous'
    | 'system'
    | 'auth-user'
    | 'staff'
    | 'client'
    | 'staff-enrollment';
  actorId?: string | null;
  targetType?: ('auth-user' | 'staff' | 'client') | null;
  targetId?: string | null;
  correlationId?: string | null;
  metadata:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'public-media';
        value: number | PublicMedia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  stableIdentifier?: T;
  title?: T;
  summary?: T;
  detailedDescription?: T;
  displayOrder?: T;
  isActive?: T;
  contentPolicy?: T;
  workingRevision?: T;
  translationWorkflow?:
    | T
    | {
        en?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
        es?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
      };
  urgentPublicationControls?:
    | T
    | {
        expiresAt?: T;
        translationOwner?: T;
        translationFollowUpDeadline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-media_select".
 */
export interface PublicMediaSelect<T extends boolean = true> {
  assetType?: T;
  altText?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  workEmail?: T;
  role?: T;
  status?: T;
  isPrimaryOwner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  clientNumber?: T;
  firstName?: T;
  lastName?: T;
  contactEmail?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-identities_select".
 */
export interface PortalIdentitiesSelect<T extends boolean = true> {
  authUserId?: T;
  subjectType?: T;
  staff?: T;
  client?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-events_select".
 */
export interface SecurityEventsSelect<T extends boolean = true> {
  occurredAt?: T;
  action?: T;
  actorKind?: T;
  actorId?: T;
  targetType?: T;
  targetId?: T;
  correlationId?: T;
  metadata?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-identity".
 */
export interface BusinessIdentity {
  id: number;
  /**
   * The legally recognized name. Do not translate or infer this value.
   */
  legalBusinessName?: string | null;
  publicDisplayName: string;
  shortName?: string | null;
  tagline?: string | null;
  businessDescription?: string | null;
  serviceAreaDescription?: string | null;
  /**
   * Requires qualified bilingual review before publication.
   */
  publicDisclaimer?: string | null;
  primaryLogo?: (number | null) | PublicMedia;
  compactLogo?: (number | null) | PublicMedia;
  brandingStatus: 'established' | 'rebranding';
  rebrandingNotice?: string | null;
  /**
   * Controls the server-side bilingual review and publication policy.
   */
  contentPolicy: 'evergreen' | 'legal' | 'urgent-announcement';
  workingRevision: number;
  /**
   * Workflow metadata is editorial-only and must never include client-sensitive information.
   */
  translationWorkflow: {
    en: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
    es: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
  };
  /**
   * Required when an urgent announcement is published in one locale before the other.
   */
  urgentPublicationControls?: {
    expiresAt?: string | null;
    translationOwner?: (number | null) | CmsUser;
    translationFollowUpDeadline?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  /**
   * Approved public telephone number only.
   */
  approvedTelephone?: string | null;
  /**
   * Approved business WhatsApp number only.
   */
  approvedWhatsAppNumber?: string | null;
  /**
   * Approved general-contact mailbox only.
   */
  approvedGeneralEmail?: string | null;
  officeAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    countryCode?: string | null;
  };
  businessHours?:
    | {
        day:
          | 'monday'
          | 'tuesday'
          | 'wednesday'
          | 'thursday'
          | 'friday'
          | 'saturday'
          | 'sunday';
        closed?: boolean | null;
        opensAt?: string | null;
        closesAt?: string | null;
        id?: string | null;
      }[]
    | null;
  channels?: {
    telephoneEnabled?: boolean | null;
    whatsAppEnabled?: boolean | null;
    emailEnabled?: boolean | null;
  };
  /**
   * Tell clients not to send sensitive records or identifiers through public channels.
   */
  contactSafetyInstructions?: string | null;
  /**
   * Controls the server-side bilingual review and publication policy.
   */
  contentPolicy: 'evergreen' | 'legal' | 'urgent-announcement';
  workingRevision: number;
  /**
   * Workflow metadata is editorial-only and must never include client-sensitive information.
   */
  translationWorkflow: {
    en: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
    es: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
  };
  /**
   * Required when an urgent announcement is published in one locale before the other.
   */
  urgentPublicationControls?: {
    expiresAt?: string | null;
    translationOwner?: (number | null) | CmsUser;
    translationFollowUpDeadline?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-settings".
 */
export interface PortalSetting {
  id: number;
  availabilityState: 'unavailable' | 'transitioning' | 'available';
  transitionNotice?: string | null;
  signInPlaceholderHeading?: string | null;
  signInPlaceholderMessage?: string | null;
  /**
   * Controls the server-side bilingual review and publication policy.
   */
  contentPolicy: 'evergreen' | 'legal' | 'urgent-announcement';
  workingRevision: number;
  /**
   * Workflow metadata is editorial-only and must never include client-sensitive information.
   */
  translationWorkflow: {
    en: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
    es: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
  };
  /**
   * Required when an urgent announcement is published in one locale before the other.
   */
  urgentPublicationControls?: {
    expiresAt?: string | null;
    translationOwner?: (number | null) | CmsUser;
    translationFollowUpDeadline?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content".
 */
export interface HomepageContent {
  id: number;
  hero?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
  };
  servicesIntroduction?: {
    heading?: string | null;
    body?: string | null;
  };
  processSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  portalIntroduction?: {
    heading?: string | null;
    body?: string | null;
  };
  trustSection?: {
    heading?: string | null;
    body?: string | null;
  };
  callToAction?: {
    heading?: string | null;
    body?: string | null;
    primaryLabel?: string | null;
    secondaryLabel?: string | null;
  };
  footerCopy?: string | null;
  /**
   * Controls the server-side bilingual review and publication policy.
   */
  contentPolicy: 'evergreen' | 'legal' | 'urgent-announcement';
  workingRevision: number;
  /**
   * Workflow metadata is editorial-only and must never include client-sensitive information.
   */
  translationWorkflow: {
    en: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
    es: {
      state: 'draft' | 'needs-review' | 'reviewed' | 'published';
      sourceRevision: number;
      reviewedBy?: (number | null) | CmsUser;
      reviewedAt?: string | null;
      publishedBy?: (number | null) | CmsUser;
      publishedAt?: string | null;
      lastEditedBy?: (number | null) | CmsUser;
      lastEditedAt?: string | null;
      /**
       * Editorial context only. Never enter client names, identifiers, records, or case details.
       */
      reviewNotes?: string | null;
    };
  };
  /**
   * Required when an urgent announcement is published in one locale before the other.
   */
  urgentPublicationControls?: {
    expiresAt?: string | null;
    translationOwner?: (number | null) | CmsUser;
    translationFollowUpDeadline?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-identity_select".
 */
export interface BusinessIdentitySelect<T extends boolean = true> {
  legalBusinessName?: T;
  publicDisplayName?: T;
  shortName?: T;
  tagline?: T;
  businessDescription?: T;
  serviceAreaDescription?: T;
  publicDisclaimer?: T;
  primaryLogo?: T;
  compactLogo?: T;
  brandingStatus?: T;
  rebrandingNotice?: T;
  contentPolicy?: T;
  workingRevision?: T;
  translationWorkflow?:
    | T
    | {
        en?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
        es?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
      };
  urgentPublicationControls?:
    | T
    | {
        expiresAt?: T;
        translationOwner?: T;
        translationFollowUpDeadline?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  approvedTelephone?: T;
  approvedWhatsAppNumber?: T;
  approvedGeneralEmail?: T;
  officeAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        countryCode?: T;
      };
  businessHours?:
    | T
    | {
        day?: T;
        closed?: T;
        opensAt?: T;
        closesAt?: T;
        id?: T;
      };
  channels?:
    | T
    | {
        telephoneEnabled?: T;
        whatsAppEnabled?: T;
        emailEnabled?: T;
      };
  contactSafetyInstructions?: T;
  contentPolicy?: T;
  workingRevision?: T;
  translationWorkflow?:
    | T
    | {
        en?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
        es?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
      };
  urgentPublicationControls?:
    | T
    | {
        expiresAt?: T;
        translationOwner?: T;
        translationFollowUpDeadline?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-settings_select".
 */
export interface PortalSettingsSelect<T extends boolean = true> {
  availabilityState?: T;
  transitionNotice?: T;
  signInPlaceholderHeading?: T;
  signInPlaceholderMessage?: T;
  contentPolicy?: T;
  workingRevision?: T;
  translationWorkflow?:
    | T
    | {
        en?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
        es?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
      };
  urgentPublicationControls?:
    | T
    | {
        expiresAt?: T;
        translationOwner?: T;
        translationFollowUpDeadline?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content_select".
 */
export interface HomepageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
      };
  servicesIntroduction?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  portalIntroduction?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  trustSection?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  callToAction?:
    | T
    | {
        heading?: T;
        body?: T;
        primaryLabel?: T;
        secondaryLabel?: T;
      };
  footerCopy?: T;
  contentPolicy?: T;
  workingRevision?: T;
  translationWorkflow?:
    | T
    | {
        en?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
        es?:
          | T
          | {
              state?: T;
              sourceRevision?: T;
              reviewedBy?: T;
              reviewedAt?: T;
              publishedBy?: T;
              publishedAt?: T;
              lastEditedBy?: T;
              lastEditedAt?: T;
              reviewNotes?: T;
            };
      };
  urgentPublicationControls?:
    | T
    | {
        expiresAt?: T;
        translationOwner?: T;
        translationFollowUpDeadline?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
