import type { Field } from 'payload';
import { describe, expect, it } from 'vitest';

import { Clients, validateClientStatus } from './collection';
import { enforceClientInvariants } from './invariants';

function namedField(name: string): Field & { name: string } {
  const field = Clients.fields.find(
    (candidate): candidate is Field & { name: string } =>
      'name' in candidate && candidate.name === name,
  );

  if (field === undefined) throw new Error(`Missing Client field ${name}.`);
  return field;
}

async function applyInvariants(
  operation: 'create' | 'update',
  data: Record<string, unknown>,
): Promise<Record<string, unknown>> {
  const result = await enforceClientInvariants({
    data,
    operation,
  } as Parameters<typeof enforceClientInvariants>[0]);

  if (result === undefined || Array.isArray(result)) {
    throw new Error('Client invariant hook returned invalid data.');
  }

  return result;
}

describe('Clients collection', () => {
  it('contains only the approved Slice 1 domain fields', () => {
    const fieldNames = Clients.fields.flatMap((field) =>
      'name' in field ? [field.name] : [],
    );

    expect(fieldNames).toEqual([
      'clientNumber',
      'firstName',
      'lastName',
      'contactEmail',
      'status',
    ]);
    expect(Clients.auth).toBeUndefined();
    expect(Clients.timestamps).toBe(true);

    const prohibitedFields = [
      'password',
      'credential',
      'loginEmail',
      'betterAuthUserId',
      'role',
      'portalStatus',
      'invitationStatus',
      'activationStatus',
      'address',
      'phone',
      'taxId',
      'immigrationId',
      'governmentId',
      'household',
      'case',
      'document',
      'message',
      'payment',
    ];

    expect(fieldNames).not.toEqual(expect.arrayContaining(prohibitedFields));
  });

  it('creates a minimal Client without credential or portal fields', async () => {
    const result = await applyInvariants('create', {
      contactEmail: '  Contact@Example.COM ',
      firstName: 'Ada',
      lastName: 'Lovelace',
      status: 'active',
    });

    expect(result).toMatchObject({
      contactEmail: 'contact@example.com',
      firstName: 'Ada',
      lastName: 'Lovelace',
      status: 'active',
    });
    expect(result.clientNumber).toMatch(
      /^CL-[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}$/,
    );
    expect(result).not.toHaveProperty('credential');
    expect(result).not.toHaveProperty('role');
    expect(result).not.toHaveProperty('portalStatus');
  });

  it('keeps contact email separate from identity and permits shared contacts', () => {
    const contactEmail = namedField('contactEmail');

    expect(contactEmail).toMatchObject({
      required: true,
      type: 'email',
    });
    expect('unique' in contactEmail && contactEmail.unique).not.toBe(true);
  });

  it('rejects caller-supplied Client numbers', async () => {
    await expect(
      applyInvariants('create', {
        clientNumber: 'CL-7F4K-92MX',
      }),
    ).rejects.toThrow('generated by the server');
  });

  it('rejects Client-number mutation, including a submitted unchanged value', async () => {
    await expect(
      applyInvariants('update', {
        clientNumber: 'CL-7F4K-92MX',
      }),
    ).rejects.toThrow('cannot be changed');
  });

  it('accepts only active or inactive business status', () => {
    const status = namedField('status');

    if (status.type !== 'select' || status.validate === undefined) {
      throw new Error('Client status field is not a validated select.');
    }

    expect(status.validate).toBe(validateClientStatus);
    expect(validateClientStatus('active')).toBe(true);
    expect(validateClientStatus('inactive')).toBe(true);
    expect(validateClientStatus('disabled')).toBe(
      'Client status must be active or inactive.',
    );
  });

  it('declares the Client number immutable, indexed, and database-unique', () => {
    const clientNumber = namedField('clientNumber');

    expect(clientNumber).toMatchObject({
      admin: { readOnly: true },
      index: true,
      required: true,
      type: 'text',
      unique: true,
    });
  });
});
