import {
  APIError,
  type CollectionBeforeValidateHook,
  type TypeWithID,
} from 'payload';

import { generateClientNumber } from './client-number-service';
import { normalizeContactEmail } from './contact-email';

export const enforceClientInvariants: CollectionBeforeValidateHook<
  TypeWithID & Record<string, unknown>
> = ({ data, operation }) => {
  const nextData = { ...data };

  if (nextData.clientNumber !== undefined) {
    throw new APIError(
      operation === 'create'
        ? 'Client number is generated by the server and cannot be supplied.'
        : 'Client number cannot be changed.',
      400,
    );
  }

  if (operation === 'create') {
    nextData.clientNumber = generateClientNumber();
  }

  if (nextData.contactEmail !== undefined) {
    const contactEmail = normalizeContactEmail(nextData.contactEmail);

    if (contactEmail === undefined) {
      throw new APIError('Client contact email must be valid.', 400);
    }

    nextData.contactEmail = contactEmail;
  }

  return nextData;
};
